apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: baseline
  namespace: shared-services
  labels:
    kustomize.toolkit.fluxcd.io/name: baseline
    kustomize.toolkit.fluxcd.io/namespace: shared-services
  finalizers:
  - finalizers.fluxcd.io
spec:
  force: false
  interval: 10m0s
  path: ./base
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster
    namespace: flux-system
  dependsOn:
  - name: shared-services
  kubeConfig:
    secretRef:
      name: arbol-kubeconfig
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
