apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: shared-services
  namespace: shared-services
  labels:
    kustomize.toolkit.fluxcd.io/name: shared-services
    kustomize.toolkit.fluxcd.io/namespace: shared-services
  finalizers:
  - finalizers.fluxcd.io
spec:
  force: false
  interval: 10m0s
  path: ./base/shared-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-cluster
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
