apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: contour
  namespace: projectcontour
  labels:
    kustomize.toolkit.fluxcd.io/name: contour
    kustomize.toolkit.fluxcd.io/namespace: projectcontour
  finalizers:
  - finalizers.fluxcd.io
spec:
  force: false
  interval: 10m0s
  path: ./base/projectcontour
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-cluster
    namespace: flux-system
