apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
  labels:
    kustomize.toolkit.fluxcd.io/name: cert-manager
    kustomize.toolkit.fluxcd.io/namespace: cert-manager
  finalizers:
  - finalizers.fluxcd.io
spec:
  interval: 10m0s
  path: ./base/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: management-cluster
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
