apiVersion: v1
kind: Secret
metadata:
    name: services-deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RDKkoVtenlpL4zjLqeWHCFCcHgvXP03g1WvuBJkE6cYL8C/YOJLui48GYXzFeJAlJuY9oW1xpJeIRTtbnIXMBIjVu8husfn9cODp5rZz1fpKC0IzMHCBzjn2KBecCsOJ7aFwhC27frOWCU36FgAMD9SN+ud7hk8DJ4gp9QjEdquSjHTKsgwBUh95/+M/UCycYchBN7EqIBTO11WsVLl1sBulBcZ80I8oSxcVRoQmcB16kkglCqlNIgkE4u7LyuZEPEp9PR6ZkMye1KiITJ9jIc66d69aftEZOjTnvTmk4XgqpZjkAoodW/Yhc0I5wIHkqGHh39lEugP0Zq7jx9OvZxha1qqbZTtpGu3HtZRaQMFh4RK/redVFUHTLsP2KtBE3dBxb4FpAsZllCrTUpgdG5jP,iv:5BaQW80cP9EBl1ELzXhLNU94IOwXCSmJwssesEMVM54=,tag:4RCxxFOD+UhdZB1C81Ur2A==,type:str]
    identity.pub: ENC[AES256_GCM,data:oeNv/fuvcVua1e2edvTN4X5ZRe7u/B9Bzm9o4CdBTN6zEEmCduO9uKartmJabR16eauQ42P0xafkMYgsfTDEABqxfHlp1kpvCqHvRMN9IlyztXlJ24q/3ovu+N1LvlglbAYd+sYxIYlrAhqwigaJGoC5xR/DbcLoYFKIfO5JdnQ/oD3gqn0GKfCMxjli8dbMVV6Z8nf5fgyGicdHIRC+GsCoKDY3k5iO/vIRXdhtTFc1cLYe+qkT25Etl36hHPGnFGECNHoFESwnLUZZrg==,iv:9J4X2Aq4V74vOVDby/ESAkuftWQ/i6rnhrroxfpPqmo=,tag:5pJuJG7NFgvWHu9Opwu0ZQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:X2lZJTFbldN+/4d4mQpUscDAa3f2osNU66bSmc2ijycdY3OnQRE4RRri7CmPgN5gua9wI4tORz+CrjBqLQsnCx8OWONL2nfm2hgnfDhFMlUxi6I1QWlO8JQ5n4rjH5R4e6WtgZEsLbEpM9RGf/ebViCxhI83qZ7GTBCR4QUhDt5nv9oll+3m0iSLv1Z56jfvkOKFtIjgDy4ipo5d/JSYKUInsa9wf3xbQwGB,iv:FN5QB5YQ8EJC/zSIyPdczdEGLklYwbxf0b6lnzl5lvk=,tag:vP3QQSp5ul0svlORZefrlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-11T16:39:09Z"
    mac: ENC[AES256_GCM,data:jXhssJZ2tNgivhiV4VbkwYHuG3rsmMEcxDKxoar4sy3oBDQb1srGzynI2q4bSwYI6LTLDAIRRwi5XFwZAwCJGTgwwbx8RJga/IaOBMh79U0zPkw/stndIxQatV2EchB9+3QgAIe+De9M3t9secs6bhP1K3x4fraOgyW7S8Ebfoo=,iv:5IjNCgOHS0Vx7l+Mvc1T2ZtJSsRcUXC9vzKtV71Cr2A=,tag:QoB0TVGbhy8hoCwl91KswQ==,type:str]
    pgp:
        - created_at: "2022-12-11T16:39:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA9VhhrDDnyi5AQ//bONLdFa9HItqQpKac38WWeEGM+85Pa5JxuKZf6zotZUg
            AQC9dIyeuQ+Pg64GZt0C107o9+9YB7GWrmpFW1GyRze+0dipjW89k/cl/p6wn4Lv
            WfHdBNeWZjSvPEb0Rsm1EszIcUpBPwKCi/luHhrkxGSAjqG1C+7C8PCRE14oFx8P
            nWNi/YOoYfNxxIHn0HImqb3kpx1gkvmSFi3smfg2ZwFE9J1UmVhrLOVF0/t8LFwt
            AlVfHxQMD74TaCNLMKbsthvZ/ICLenzH5hL2f+Yg4900FQLPsqVaF0rw4T8Ob1AY
            qoBgloLkgqHE/mHqQVSv92Nz0qzX0SomoT/0Abu+QbsGqed1dZMn9EE2weNErZiK
            VD4by8BgySCpDHXU1RgySkF3dBt7K4N+lCXf2b40IeDONgqEKLSDnTwiEQkUNOlj
            x7J++ew9oqAmghhOgb9pFxTGdCkwZGinKulLPA8LR0FYZgOwn7Mp9kuP3kXTgaza
            HIwlgdZcTeyPob9xmXKoIcY8OxFbQxlyqipZA03oLCl+9tjNCAYOK9aNf6pIOIq7
            v33ONbIYcBBjBNgU1s6ueP2Bwa9oPs8cpDLJjVCLAn/LZ7ks2Rtyxo1JdUCuIfOP
            XeCnbxHs1+7zs4MeN72esVsFJYvbNISDh5YPXnTBlUwFovPnzW7W6MEpKJ37DBvS
            XgHG1zC1yAjDB0cafeeQi18GQss1TRA8HWVRlWIrqNJJpyifOfrUZW1AW/KUt8VX
            HVPqmyK9OWtWewPsF3SmiJn8oSMBs564ZIsVES7XGUcMQ55gu5UibqsWwDpMea8=
            =T1Ot
            -----END PGP MESSAGE-----
          fp: FAC1CF820538F4A07C8F4657DAD5DC6A21303194
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
